/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_danielalvarado;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author dalva
 */
public class PrincipalExamen extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalExamen
     */
    public PrincipalExamen() {
        initComponents();

        admin = new AdminUsuarios("./Usuarios.use");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearUsuario = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_Apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_NumTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jt_Username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jp_Pass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jp_PassConfirm = new javax.swing.JPasswordField();
        jb_CrearUsuario = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        js_CalidadWifi = new javax.swing.JSpinner();
        jd_VerUsuarios = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Usuarios = new javax.swing.JTable();
        jb_Llenar = new javax.swing.JButton();
        jb_Eliminar = new javax.swing.JButton();
        jb_EnviarSolicitud = new javax.swing.JButton();
        jd_LogIn = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jt_InUser = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jp_PassIn = new javax.swing.JPasswordField();
        jb_Ingresar = new javax.swing.JButton();
        jd_VerSolicitudes = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lista_Solicitudes = new javax.swing.JList<>();
        popup_ListaAmigos = new javax.swing.JPopupMenu();
        jmi_EnviarMensaje = new javax.swing.JMenuItem();
        jd_EnviarMensaje = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        text_Contenido = new javax.swing.JTextArea();
        jb_Enviar = new javax.swing.JButton();
        popup_Arbol = new javax.swing.JPopupMenu();
        jmi_LeerChats = new javax.swing.JMenuItem();
        jd_VerConversacion = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        texto_Conversacion = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbol_Receptores = new javax.swing.JTree();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_Amigos = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_Opciones = new javax.swing.JMenu();
        jmi_IngresarSesion = new javax.swing.JMenuItem();
        jmi_VerUsuarios = new javax.swing.JMenuItem();
        jmi_CrearUsuario = new javax.swing.JMenuItem();
        jmi_Solicitudes = new javax.swing.JMenuItem();

        jd_CrearUsuario.setTitle("Crear Usuario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Crear Usuario");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("NumTelefono:");

        jLabel5.setText("Username:");

        jLabel6.setText("Password:");

        jLabel7.setText("Confirm:");

        jb_CrearUsuario.setText("Crear Usuario");
        jb_CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CrearUsuarioMouseClicked(evt);
            }
        });

        jLabel8.setText("Calidad Wifi:");

        js_CalidadWifi.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));

        javax.swing.GroupLayout jd_CrearUsuarioLayout = new javax.swing.GroupLayout(jd_CrearUsuario.getContentPane());
        jd_CrearUsuario.getContentPane().setLayout(jd_CrearUsuarioLayout);
        jd_CrearUsuarioLayout.setHorizontalGroup(
            jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel1))
                    .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_Nombre)
                                    .addComponent(jt_NumTelefono)
                                    .addComponent(jp_Pass, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                                .addGap(73, 73, 73)
                                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jt_Apellido)
                                    .addComponent(jt_Username)
                                    .addComponent(jp_PassConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                            .addComponent(js_CalidadWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jb_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jd_CrearUsuarioLayout.setVerticalGroup(
            jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt_NumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_CrearUsuarioLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(61, 61, 61)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jp_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jp_PassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jd_CrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(js_CalidadWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jb_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jd_VerUsuarios.setTitle("Ver Usuarios");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Lista de Usuarios");

        tabla_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Apellido", "NumTelefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_Usuarios);

        jb_Llenar.setText("Llenar Tabla");
        jb_Llenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_LlenarMouseClicked(evt);
            }
        });

        jb_Eliminar.setText("Eliminar Usuario");
        jb_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EliminarMouseClicked(evt);
            }
        });

        jb_EnviarSolicitud.setText("Enviar Solicitud");
        jb_EnviarSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EnviarSolicitudMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_VerUsuariosLayout = new javax.swing.GroupLayout(jd_VerUsuarios.getContentPane());
        jd_VerUsuarios.getContentPane().setLayout(jd_VerUsuariosLayout);
        jd_VerUsuariosLayout.setHorizontalGroup(
            jd_VerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_VerUsuariosLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(jd_VerUsuariosLayout.createSequentialGroup()
                .addGroup(jd_VerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_VerUsuariosLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel9))
                    .addGroup(jd_VerUsuariosLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jb_Llenar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jb_EnviarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_VerUsuariosLayout.setVerticalGroup(
            jd_VerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_VerUsuariosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addGroup(jd_VerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_VerUsuariosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_VerUsuariosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jd_VerUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_Llenar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_EnviarSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );

        jd_LogIn.setTitle("Log In");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Bienvenido Usuario");

        jLabel11.setText("Username:");

        jLabel12.setText("Password:");

        jb_Ingresar.setText("Ingresar");
        jb_Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_IngresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_LogInLayout = new javax.swing.GroupLayout(jd_LogIn.getContentPane());
        jd_LogIn.getContentPane().setLayout(jd_LogInLayout);
        jd_LogInLayout.setHorizontalGroup(
            jd_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LogInLayout.createSequentialGroup()
                .addGroup(jd_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_LogInLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel10))
                    .addGroup(jd_LogInLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jd_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_InUser)
                            .addComponent(jp_PassIn, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)))
                    .addGroup(jd_LogInLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jb_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jd_LogInLayout.setVerticalGroup(
            jd_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LogInLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel10)
                .addGap(61, 61, 61)
                .addGroup(jd_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jt_InUser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jd_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jp_PassIn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jb_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jd_VerSolicitudes.setTitle("Solicitudes");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Ver Solicitudes");

        lista_Solicitudes.setModel(new DefaultListModel());
        lista_Solicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_SolicitudesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(lista_Solicitudes);

        javax.swing.GroupLayout jd_VerSolicitudesLayout = new javax.swing.GroupLayout(jd_VerSolicitudes.getContentPane());
        jd_VerSolicitudes.getContentPane().setLayout(jd_VerSolicitudesLayout);
        jd_VerSolicitudesLayout.setHorizontalGroup(
            jd_VerSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_VerSolicitudesLayout.createSequentialGroup()
                .addGroup(jd_VerSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_VerSolicitudesLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel16))
                    .addGroup(jd_VerSolicitudesLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jd_VerSolicitudesLayout.setVerticalGroup(
            jd_VerSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_VerSolicitudesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel16)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jmi_EnviarMensaje.setText("jMenuItem2");
        jmi_EnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_EnviarMensajeActionPerformed(evt);
            }
        });
        popup_ListaAmigos.add(jmi_EnviarMensaje);

        jd_EnviarMensaje.setTitle("Enviar Mensaje");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Enviar Mensaje");

        text_Contenido.setColumns(20);
        text_Contenido.setRows(5);
        jScrollPane5.setViewportView(text_Contenido);

        jb_Enviar.setText("Enviar");
        jb_Enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_EnviarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_EnviarMensajeLayout = new javax.swing.GroupLayout(jd_EnviarMensaje.getContentPane());
        jd_EnviarMensaje.getContentPane().setLayout(jd_EnviarMensajeLayout);
        jd_EnviarMensajeLayout.setHorizontalGroup(
            jd_EnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EnviarMensajeLayout.createSequentialGroup()
                .addGroup(jd_EnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_EnviarMensajeLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel17))
                    .addGroup(jd_EnviarMensajeLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_EnviarMensajeLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jb_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jd_EnviarMensajeLayout.setVerticalGroup(
            jd_EnviarMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EnviarMensajeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel17)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jb_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jmi_LeerChats.setText("Leer todo el chat");
        jmi_LeerChats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_LeerChatsMouseClicked(evt);
            }
        });
        popup_Arbol.add(jmi_LeerChats);

        jd_VerConversacion.setTitle("Ver Conversacion");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Ver Conversacion");

        texto_Conversacion.setColumns(20);
        texto_Conversacion.setRows(5);
        jScrollPane6.setViewportView(texto_Conversacion);

        javax.swing.GroupLayout jd_VerConversacionLayout = new javax.swing.GroupLayout(jd_VerConversacion.getContentPane());
        jd_VerConversacion.getContentPane().setLayout(jd_VerConversacionLayout);
        jd_VerConversacionLayout.setHorizontalGroup(
            jd_VerConversacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_VerConversacionLayout.createSequentialGroup()
                .addGroup(jd_VerConversacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_VerConversacionLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel18))
                    .addGroup(jd_VerConversacionLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jd_VerConversacionLayout.setVerticalGroup(
            jd_VerConversacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_VerConversacionLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel18)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("LeoGram");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Receptores");
        arbol_Receptores.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol_Receptores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbol_ReceptoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(arbol_Receptores);

        lista_Amigos.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(lista_Amigos);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Lista de amigos");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Arbol Receptores");

        jm_Opciones.setText("Opciones");

        jmi_IngresarSesion.setText("Ingresar Sesion");
        jm_Opciones.add(jmi_IngresarSesion);

        jmi_VerUsuarios.setText("Visualizar Usuarios");
        jm_Opciones.add(jmi_VerUsuarios);

        jmi_CrearUsuario.setText("Crear Usuario");
        jm_Opciones.add(jmi_CrearUsuario);

        jmi_Solicitudes.setText("Ver solicitudes");
        jm_Opciones.add(jmi_Solicitudes);

        jMenuBar1.add(jm_Opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(311, 311, 311))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel13)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CrearUsuarioMouseClicked
        if (jt_Nombre.getText().isEmpty() || jt_Apellido.getText().isEmpty()
                || jt_NumTelefono.getText().isEmpty() || jt_Username.getText().isEmpty()
                || jp_Pass.getText().isEmpty() || jp_PassConfirm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_CrearUsuario, "No puede dejar las casillas vacias!");
        } else {

            String pass = jp_Pass.getText();
            String cPass = jp_PassConfirm.getText();

            if (pass.equals(cPass)) {

                Usuario u = new Usuario(
                        jt_Username.getText(),
                        pass,
                        (int) js_CalidadWifi.getValue(),
                        jt_Nombre.getText(),
                        jt_Apellido.getText(),
                        jt_NumTelefono.getText()
                );

                admin.cargarArchivo();

                admin.getUsuarios().add(u);

                admin.escribirArchivo();

                JOptionPane.showMessageDialog(jd_CrearUsuario, "El usuario se creo correctamente");

            } else {
                JOptionPane.showMessageDialog(jd_CrearUsuario, "Los Passwords son distintos!");
            }

        }
    }//GEN-LAST:event_jb_CrearUsuarioMouseClicked

    private void jb_LlenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_LlenarMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla_Usuarios.getModel();
        limpiarUsuarios();

        admin.cargarArchivo();

        for (Usuario u : admin.getUsuarios()) {

            Object[] newRow = {
                u.getUsuario(),
                u.getApellido(),
                u.getNumTelefono()
            };

            modelo.addRow(newRow);

        }

        tabla_Usuarios.setModel(modelo);

    }//GEN-LAST:event_jb_LlenarMouseClicked

    private void jb_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EliminarMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla_Usuarios.getModel();
        int index = tabla_Usuarios.getSelectedRow();

        if (index >= 0) {

            admin.cargarArchivo();
            admin.getUsuarios().remove(index);
            admin.escribirArchivo();

            modelo.removeRow(index);

            JOptionPane.showMessageDialog(jd_VerUsuarios, "Se elimino el usuario correctamente");

        } else {
            JOptionPane.showMessageDialog(jd_VerUsuarios, "No hay un usuario seleccionado!");
        }

    }//GEN-LAST:event_jb_EliminarMouseClicked

    private void jb_IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_IngresarMouseClicked
        if (jt_InUser.getText().isEmpty() || jp_PassIn.getText().isEmpty()) {
            JOptionPane.showMessageDialog(jd_LogIn, "Las casillas estan vacias!");
        } else {

            String user = jt_InUser.getText();
            String pass = jp_PassIn.getText();

            admin.cargarArchivo();
            boolean logIn = false;

            userLoged = new Usuario();
            for (Usuario u : admin.getUsuarios()) {

                if (u.getUsuario().equals(user) && u.getPassword().equals(pass)) {
                    logIn = true;
                    userLoged = u;
                }
            }

            if (logIn) {

                jt_InUser.setText("");
                jp_PassIn.setText("");

                cargarAmigos();
                cargarArbol();

                JOptionPane.showMessageDialog(jd_LogIn, "Bienvenido de nuevo " + userLoged.getUsuario());
                jd_LogIn.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(jd_LogIn, "El usuario no es correcto");
            }

        }
    }//GEN-LAST:event_jb_IngresarMouseClicked

    private void lista_SolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_SolicitudesMouseClicked
        DefaultListModel modelo = (DefaultListModel) lista_Solicitudes.getModel();
        DefaultListModel modelo2 = (DefaultListModel) lista_Amigos.getModel();
        int index = lista_Solicitudes.getSelectedIndex();

        if (index >= 0) {
            Solicitud s = (Solicitud) modelo.getElementAt(index);

            int i = JOptionPane.showConfirmDialog(jd_VerSolicitudes, "" + s.getSolicitud());

            if (i == JOptionPane.OK_OPTION) {

                Usuario u = s.getUsuario();

                userLoged.getAmigos().add(u);

                modelo.remove(index);
                modelo2.addElement(u);

                admin.cargarArchivo();

                for (Usuario us : admin.getUsuarios()) {

                    if (us.getUsuario().equals(u.getUsuario())) {
                        us.getAmigos().add(userLoged);
                    }
                }

                admin.escribirArchivo();

                userLoged.getSolicitudes().remove(s);

                lista_Solicitudes.setModel(modelo);
                lista_Amigos.setModel(modelo2);

                JOptionPane.showMessageDialog(jd_VerSolicitudes, "La solicitud de amistad ha sido aceptada");

            } else {
                JOptionPane.showMessageDialog(jd_VerSolicitudes, "No se acepto la solicitud de amistad");
                userLoged.getSolicitudes().remove(s);
            }

        } else {
            JOptionPane.showMessageDialog(jd_VerSolicitudes, "No tiene solicitudes en la lista");
        }

    }//GEN-LAST:event_lista_SolicitudesMouseClicked

    private void jb_EnviarSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EnviarSolicitudMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tabla_Usuarios.getModel();
        int index = tabla_Usuarios.getSelectedRow();

        if (index >= 0) {

            Solicitud s = new Solicitud(
                    "El usuario " + userLoged.getUsuario() + " te ha enviado una solicitud de amistad",
                    userLoged
            );

            admin.cargarArchivo();

            admin.getUsuarios().get(index).getSolicitudes().add(s);

            admin.escribirArchivo();

            JOptionPane.showMessageDialog(jd_VerUsuarios, "Se envio la solicitud de amistad correctament");

        } else {
            JOptionPane.showMessageDialog(jd_VerUsuarios, "No hay un usuario seleccionado!");
        }
    }//GEN-LAST:event_jb_EnviarSolicitudMouseClicked

    private void jmi_EnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_EnviarMensajeActionPerformed

    }//GEN-LAST:event_jmi_EnviarMensajeActionPerformed

    private void jb_EnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_EnviarMouseClicked
        DefaultListModel modelo = (DefaultListModel) lista_Amigos.getModel();
        DefaultTreeModel modelt = (DefaultTreeModel) arbol_Receptores.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelt.getRoot();
        int index = lista_Amigos.getSelectedIndex();

        if (text_Contenido.getText().isEmpty()) {

            JOptionPane.showMessageDialog(jd_EnviarMensaje, "No ha escrito texto en el area");

        } else {
            SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");
            Date fecha = new Date();

            String hora = "";
            hora += fecha.getHours() + ":" + fecha.getMinutes();

            String fe = form.format(fecha);
            String texto = text_Contenido.getText();
            text_Contenido.setText("");

            Mensaje m = new Mensaje(
                    texto,
                    hora,
                    fe,
                    false
            );

            Usuario us = (Usuario) modelo.getElementAt(index);

            admin.cargarArchivo();

            Privado p = new Privado(
                    us
            );

            p.getMensajes().add(m);

            for (Usuario u : admin.getUsuarios()) {

                if (u.getUsuario().equals(us.getUsuario())) {
                    u.getChats().add(p);
                }
            }

            admin.escribirArchivo();

            userLoged.getChats().add(p);

            userLoged.getAmigos().remove(index);

            DefaultMutableTreeNode chat = new DefaultMutableTreeNode(p);

            raiz.add(chat);

            modelt.reload();

            modelo.removeElementAt(index);

            JOptionPane.showMessageDialog(this, "El mensaje se ha enviado correctamente");

        }
    }//GEN-LAST:event_jb_EnviarMouseClicked

    private void arbol_ReceptoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbol_ReceptoresMouseClicked
        DefaultTreeModel modelt = (DefaultTreeModel) arbol_Receptores.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelt.getRoot();

        if (evt.isMetaDown()) {

            if (raiz.getChildCount() > 0) {
                int row = arbol_Receptores.getClosestRowForLocation(evt.getX(), evt.getY());

                arbol_Receptores.setSelectionRow(row);

                Object v1 = arbol_Receptores.getSelectionPath().getLastPathComponent();

                chatSeleccionado = (DefaultMutableTreeNode) v1;

                if (chatSeleccionado.getUserObject() instanceof Chats) {
                   

                    chatSelected = (Chats) chatSeleccionado.getUserObject();
                    popup_Arbol.show(arbol_Receptores, evt.getX(), evt.getY());
                }
            }
        }
    }//GEN-LAST:event_arbol_ReceptoresMouseClicked

    private void jmi_LeerChatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_LeerChatsMouseClicked
        
        if(chatSelected instanceof Privado){
            
            Privado p = (Privado)chatSelected;
            
            texto_Conversacion.setText("");
            
            for (Mensaje m : p.getMensajes()) {
                texto_Conversacion.append(m.getHora()+""+m.getFecha()+""+m.getContenido());
                texto_Conversacion.append("\n");
            }
            
            for (Mensaje m : p.getMensajes()) {
                m.setLeido(true);
            }
            
        }else{
            
            texto_Conversacion.setText("");
            
            Grupo g = (Grupo)chatSelected;
            
            for (Mensaje m : g.getMensajes()) {
                texto_Conversacion.append(m.getFecha()+""+m.getFecha()+""+m.getContenido());
                texto_Conversacion.append("\n");
            }
            
            for (Mensaje m : g.getMensajes()) {
                m.setLeido(true);
            }
        }
    }//GEN-LAST:event_jmi_LeerChatsMouseClicked

    public void cargarAmigos() {
        DefaultListModel modelo = (DefaultListModel) lista_Amigos.getModel();

        for (Usuario amigo : userLoged.getAmigos()) {
            modelo.addElement(amigo);
        }

        lista_Amigos.setModel(modelo);
    }

    public void cargarArbol() {
        DefaultTreeModel modelt = (DefaultTreeModel) arbol_Receptores.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelt.getRoot();

        for (Chats chat : userLoged.getChats()) {

            DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(chat);

            raiz.add(nodo);
        }

        modelt.reload();
    }

    public void limpiarUsuarios() {
        tabla_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Username", "Apellido", "NumTelefono"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, true, true
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol_Receptores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jb_CrearUsuario;
    private javax.swing.JButton jb_Eliminar;
    private javax.swing.JButton jb_Enviar;
    private javax.swing.JButton jb_EnviarSolicitud;
    private javax.swing.JButton jb_Ingresar;
    private javax.swing.JButton jb_Llenar;
    private javax.swing.JDialog jd_CrearUsuario;
    private javax.swing.JDialog jd_EnviarMensaje;
    private javax.swing.JDialog jd_LogIn;
    private javax.swing.JDialog jd_VerConversacion;
    private javax.swing.JDialog jd_VerSolicitudes;
    private javax.swing.JDialog jd_VerUsuarios;
    private javax.swing.JMenu jm_Opciones;
    private javax.swing.JMenuItem jmi_CrearUsuario;
    private javax.swing.JMenuItem jmi_EnviarMensaje;
    private javax.swing.JMenuItem jmi_IngresarSesion;
    private javax.swing.JMenuItem jmi_LeerChats;
    private javax.swing.JMenuItem jmi_Solicitudes;
    private javax.swing.JMenuItem jmi_VerUsuarios;
    private javax.swing.JPasswordField jp_Pass;
    private javax.swing.JPasswordField jp_PassConfirm;
    private javax.swing.JPasswordField jp_PassIn;
    private javax.swing.JSpinner js_CalidadWifi;
    private javax.swing.JTextField jt_Apellido;
    private javax.swing.JTextField jt_InUser;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_NumTelefono;
    private javax.swing.JTextField jt_Username;
    private javax.swing.JList<String> lista_Amigos;
    private javax.swing.JList<String> lista_Solicitudes;
    private javax.swing.JPopupMenu popup_Arbol;
    private javax.swing.JPopupMenu popup_ListaAmigos;
    private javax.swing.JTable tabla_Usuarios;
    private javax.swing.JTextArea text_Contenido;
    private javax.swing.JTextArea texto_Conversacion;
    // End of variables declaration//GEN-END:variables

    AdminUsuarios admin;
    Usuario userLoged;
    
    DefaultMutableTreeNode chatSeleccionado;
    Chats chatSelected;

}
